	DROP SCHEMA IF EXISTS EJERCICIO_10;
    
    CREATE SCHEMA EJERCICIO_10;
    
    USE EJERCICIO_10;
    
CREATE TABLE AEROPUERTO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(50) UNIQUE NOT NULL,
	CIUDAD VARCHAR (20),
	PAÍS VARCHAR (20)
);

INSERT INTO AEROPUERTO(NOMBRE) VALUES
("MÁLAGA"),
("BILBAO");

SELECT * FROM AEROPUERTO;


CREATE TABLE PROGRAMA_VUELO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	LÍNEA VARCHAR(30),
	ID_DESPEGA INT,
	ID_ATERRIZA INT,
    
    FOREIGN KEY (ID_DESPEGA) REFERENCES AEROPUERTO(ID),
    FOREIGN KEY (ID_ATERRIZA) REFERENCES AEROPUERTO(ID)
    
);

INSERT INTO PROGRAMA_VUELO VALUES
(DEFAULT, "IBERIA", 23, 2);

SELECT * FROM PROGRAMA_VUELO;

CREATE TABLE PROGRAMA_VUELA_DÍAS(
	ID_PROGRAMA INT,
    DÍA_SEMANA ENUM("LUNES", "MARTES", "MIÉRCOLES", "JUEVES", "VIERNES", "SÁBADO", "DOMINGO"), #MEJOR FORMA Y MÁS LIMPIA PARA PONER ESTE TIPO DE DATO.
    
    PRIMARY KEY (ID_PROGRAMA, DÍA_SEMANA),
    
    FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMA_VUELO(ID)
);

CREATE TABLE MODELO_AVIÓN(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    LONGITUD_METROS FLOAT,
    ANCHO_METROS FLOAT,
    NÚMERO_PLAZAS SMALLINT DEFAULT 50,
    
    CONSTRAINT LONGITUD_MAS_0 CHECK(LONGITUD_METROS>0),
    CONSTRAINT ANCHO_MAS_0 CHECK(ANCHO_METROS>0)
);

INSERT INTO MODELO_AVIÓN VALUES
(DEFAULT, 38.6, 50,70);

SELECT * FROM MODELO_AVIÓN;


CREATE TABLE VUELO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NÚMERO_VUELO INT,
	MATRÍCULA VARCHAR(10) NOT NULL,
	HORA_DESPEGUE DATETIME,
	HORA_ATERRIZAJE DATETIME,
    ID_PROGRAMA INT,
    ID_MODELO INT,
    
    FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMA_VUELO(ID),
    FOREIGN KEY (ID_MODELO) REFERENCES MODELO_AVIÓN(ID),
    
    CONSTRAINT ATERRIZAJE_MAS_DESPEGUE CHECK(HORA_ATERRIZAJE>HORA_DESPEGUE)
);


    
CREATE TABLE MODELO_PUEDE_ATERRIZAR_AEROPUERTO(
	ID_MODELO INT, 
	ID_AEROPUERTO INT,
    
    PRIMARY KEY (ID_MODELO, ID_AEROPUERTO),
    
    FOREIGN KEY (ID_MODELO) REFERENCES MODELO_AVIÓN(ID),
    FOREIGN KEY (ID_AEROPUERTO) REFERENCES AEROPUERTO(ID)
    
);

INSERT INTO MODELO_PUEDE_ATERRIZAR_AEROPUERTO VALUES
(1,54);

SELECT * FROM MODELO_PUEDE_ATERRIZAR_AEROPUERTO;