DROP SCHEMA IF EXISTS EJERCICIO_6;

CREATE SCHEMA EJERCICIO_6;

USE EJERCICIO_6;

CREATE TABLE ESPECIE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE_CIENTÍFICO VARCHAR(50) NOT NULL,
	DESCRIPCIÓN TEXT,
	FOTOGRAFÍA MEDIUMBLOB
);

CREATE TABLE ESPECIE_TIENE_NOMBRE_COMÚN(
	ID_ESPECIE INT,
	NOMBRE_COMÚN VARCHAR(35) NOT NULL,
    
    PRIMARY KEY (ID_ESPECIE, NOMBRE_COMÚN),
    FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIE(ID)
);


CREATE TABLE HÁBITAT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(30) NOT NULL,
	CLIMA VARCHAR(30),
	VEGETACIÓN VARCHAR(50)
);

INSERT INTO HÁBITAT(NOMBRE) VALUES
("JUNGLA"),
("DESIERTO"),
("ÁRTICO");

SELECT * FROM HÁBITAT;

CREATE TABLE ITINERARIO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	DURACIÓN_HORAS TIME DEFAULT "01:00:00",
	LONGITUD_METROS FLOAT,
	MÁXIMO_VISITANTES TINYINT,
    
    CONSTRAINT MÁXIMO_VISITANTES_0_100 CHECK (MÁXIMO_VISITANTES BETWEEN 1 AND 100)
);

CREATE TABLE ESPECIE_VIVE_HÁBITAT(
	ID_ESPECIE INT,
	ID_HÁBITAT INT,
	ÍNDICE_VULNERABILIDAD VARCHAR(30),
    
    PRIMARY KEY (ID_ESPECIE, ID_HÁBITAT, ÍNDICE_VULNERABILIDAD),
    FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIE(ID),
    FOREIGN KEY (ID_HÁBITAT) REFERENCES HÁBITAT(ID) 
);

CREATE TABLE ITINERARIO_RECORRE_HÁBITAT(
	ID_HÁBITAT INT,
	ID_ITINERARIO INT,
    
    PRIMARY KEY (ID_HÁBITAT, ID_ITINERARIO),
    FOREIGN KEY (ID_HÁBITAT) REFERENCES HÁBITAT(ID),
    FOREIGN KEY (ID_ITINERARIO) REFERENCES ITINERARIO(ID)
);

INSERT INTO ESPECIE VALUES
(DEFAULT, "",),
(),
();

INSERT INTO ESPECIE_VIVE_HÁBITAT VALUES
(1, 2, "BUENO"),
(2, 3, "REGULAR"),
(3, 4, "MALA");

SELECT * FROM ESPECIE_VIVE_HÁBITAT;

#INSERT INTO ITINERARIO(DURACIÓN_HORAS, MÁXIMO_VISITANTES) VALUES
#("05:00:00", 60),
#("00:30:00", 80),
#("36:00:00", 100);

#SELECT * FROM ITINERARIO;

# PARA INSERTAR DATOS

# INSERT INTO ESPECIE VALUES() (EN ESPECIE ES LA TABLA DONDE VAMOS A INSERTAR LOS DATOS).
# (DEFAULT, "PERRUS CANNIS", "DESCRIPCIÓN", NULL(FOTO));


# PARA VER UNA TABLA ES:

#SELECT * FROM ESPECIE
# INSERT INTO ESPECIE VALUES(NOMBRE_CIENTÍFICO) VALUES SI LO PONEMOS ASI SOLO COGE LOS DATOS DE ESA COLUMNA EN ESTE CASO NOMBRE_CIENTÍFICO.
#("OTRUS BITCHIS");