DROP SCHEMA IF EXISTS EJERCICIO_15;
CREATE SCHEMA EJERCICIO_15;

USE EJERCICIO_15;

CREATE TABLE PARTICIPANTE (
ID INT PRIMARY KEY AUTO_INCREMENT,
 DNI VARCHAR (9) UNIQUE NOT NULL,
 NOMBRE VARCHAR (50) NOT NULL,
 EDAD TINYINT ,
 CONSTRAINT EDAD_MINIMA CHECK (EDAD >= 18)
 
 );
 
 CREATE TABLE ORGANIZADOR (
ID INT PRIMARY KEY AUTO_INCREMENT,
 EDAD TINYINT,
 CARGO VARCHAR (50),
 FECHA_INICIO DATE,
 CONSTRAINT EDAD_MINIMA_OR CHECK (EDAD >= 18)
 ) ;
 INSERT INTO ORGANIZADOR VALUES 
 (DEFAULT,20,"ESE MISMO","2024/05/23"),
 (DEFAULT,30,"YO MISMO","2024/05/23"),
 (DEFAULT,40,"OTRO MISMO","2024/05/23");
 
 SELECT * FROM ORGANIZADOR;
 
 CREATE TABLE DIRECTOR (
ID_ORGANIZADOR INT,
 AÑOS_EXPERIENCIA TINYINT,
 
 PRIMARY KEY (ID_ORGANIZADOR),
 FOREIGN KEY (ID_ORGANIZADOR) REFERENCES ORGANIZADOR (ID),
 CONSTRAINT EDADA_MINIMA CHECK (AÑOS_EXPERIENCIA >= 5)
 ) ;
  INSERT INTO DIRECTOR VALUES 
  (1, 5),
  (2, 7),
  (3, 22);
  SELECT * FROM DIRECTOR;
  
CREATE TABLE CARRERA (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 FECHA DATETIME, 
 LUGAR_INICIO VARCHAR (30),
 LUGAR_FIN VARCHAR (30),
 ID_DIRECTOR INT,
 
 FOREIGN KEY (ID_DIRECTOR) REFERENCES DIRECTOR (ID_ORGANIZADOR)
 ); 
CREATE TABLE ETAPA (
ID INT PRIMARY KEY AUTO_INCREMENT,
 NÚMERO_ETAPA TINYINT,
 LONGITUD_KM FLOAT ,
 ID_CARRERA INT,
 
 FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID),
 CONSTRAINT LONGITUD_MAX_100 CHECK (LONGITUD_KM BETWEEN 0 AND 100)
 ); 

CREATE TABLE CARRERA_CICLISTA (
ID_CARRERA INT, 
TIPO_TERRENO VARCHAR (30),

PRIMARY KEY (ID_CARRERA),
FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
); 

CREATE TABLE CARRERA_A_PIE (
ID_CARRERA INT,
DESNIVEL_TOTAL_METROS FLOAT DEFAULT 0,

PRIMARY KEY (ID_CARRERA),
FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
 ) ;

CREATE TABLE BICICLETA (
ID INT PRIMARY KEY AUTO_INCREMENT, 
MODELO VARCHAR (30), 
ES_ELÉCTRICA BOOL, 
PESO_GRAMOS FLOAT DEFAULT 100
) ;
CREATE TABLE BICICLETA_PERMITIDA (
ID_CARRERA_CICLISTA INT ,
 ID_BICICLETA INT,
 
 PRIMARY KEY (ID_CARRERA_CICLISTA,ID_BICICLETA),
 FOREIGN KEY (ID_CARRERA_CICLISTA) REFERENCES CARRERA_CICLISTA(ID_CARRERA),
 FOREIGN KEY (ID_BICICLETA) REFERENCES BICICLETA(ID)
 ) ;
 
CREATE TABLE PARTICIPANTE_PARTICIPA_CARRERA (
ID_PARTICIPANTE INT,
 ID_CARRERA INT, 
 NÚMERO_DORSAL SMALLINT UNSIGNED ,
 
 UNIQUE(ID_CARRERA,NÚMERO_DORSAL),
 
 PRIMARY KEY (ID_PARTICIPANTE,ID_CARRERA),
 FOREIGN KEY (ID_PARTICIPANTE) REFERENCES PARTICIPANTE(ID),
 FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
 ); 
 
CREATE TABLE ORGANIZADOR_ORGANIZA_CARRERA (
ID_ORGANIZADOR INT,
 ID_CARRERA INT,
 PRIMARY KEY (ID_ORGANIZADOR,ID_CARRERA),
 FOREIGN KEY (ID_ORGANIZADOR) REFERENCES ORGANIZADOR(ID),
 FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
 );
 

 
 