#ESTO SIRVE PARA ELIMINAR LA BASE DE DATOS.
DROP SCHEMA IF EXISTS PRIMERA_CHAMBA; 
#SI QUEREMOS QUE SALGA EL WARNING SE PONE IF EXISTS. POR LO QUE SI EXISTE PRIMERA CHAMBA LO BORRA Y SI NO EXISTE MANDA UN AVISO.

#ESTO SIRVE PARA CREAR NUESTRA BASE DE DATOS
CREATE SCHEMA PRIMERA_CHAMBA;

USE PRIMERA_CHAMBA; # ESTO INDICA EN DONDE VAMOS A CREAR LA TABLA

#PARA CREAR TABLAS Y ENTRE PARÉNTESIS SUS ATRIBUTOS.
CREATE TABLE TABLA(
	ID INT PRIMARY KEY AUTO_INCREMENT, # ESTO HACE QUE NOS CREE UN ID AUTOMÁTICO SIN TENER QUE PONERLO NOSOTROS.
	NOMBRE VARCHAR(20), # EL 20 ES EL TAMAÑO MÁXIMO.
    DNI CHAR(9), # SI VEMOS QUE ALGO NO CAMBIA POR EJEMPLO COMO EL DNI PONEMOS CHAR PARA DEJARLO FIJO.
    EDAD TINYINT,
    DINERO DECIMAL(5,2) # PARA TENER MÁS PRECISIÓN USAMOS DECIMAL, SIEMPRE LO USAREMOS EN EL TEMA DE DINERO.
);

CREATE TABLE OTRA_TABLA(
ID INT PRIMARY KEY AUTO_INCREMENT,
TAMAÑO FLOAT,
FOTO MEDIUMBLOB,
FECHA DATE,
HORA TIME,
ID_TABLA INT, # ESTO ES UNA FOREIGN KEY A TABLA.

FOREIGN KEY (ID_TABLA) REFERENCES TABLA(ID)
);


# SI ES SUBRAYADO CON FOSFORITO Y EN NEGRITA ES PK
# SI ESTA SUBRAYADO CON FOSFORITO SIN NEGRITA ES FK

# PARA LAS PK COMPUESTA
CREATE TABLE TABLA_USA_OTRA_TABLA(
	ID_TABLA INT,
    ID_OTRA_TABLA INT,
    
    PRIMARY KEY(ID_TABLA, ID_OTRA_TABLA), #LA PRIMARY KEY ES COMPUESTA
    
    FOREIGN KEY (ID_TABLA) REFERENCES TABLA(ID),
    FOREIGN KEY (ID_OTRA_TABLA) REFERENCES OTRA_TABLA(ID)
);