DROP SCHEMA IF EXISTS REPASO_9;
CREATE SCHEMA REPASO_9;

USE REPASO_9;

CREATE TABLE CLIENTE(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
	NOMBRE VARCHAR (30),
	SALDO_EUROS DECIMAL(9,2)
 );
 
CREATE TABLE CLIENTE_TIENE_DIRECCIÓN (
	ID_CLIENTE INT, 
	DIRECCIÓN VARCHAR (50),
    PRIMARY KEY (ID_CLIENTE,DIRECCIÓN),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
) ;
CREATE TABLE ARTÍCULO (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
	NOMBRE VARCHAR (50)
);
 
CREATE TABLE ALMACÉN (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	TELÉFONO VARCHAR (15), 
	TOTAL_ARTÍCULOS INT
 ) ;
 
CREATE TABLE ALMACÉN_PROVEE_ARTÍCULO (
ID_ALMACÉN INT, 
ID_ARTÍCULO INT, 
STOCK INT ,
PRIMARY KEY (ID_ALMACÉN,ID_ARTÍCULO),
FOREIGN KEY (ID_ALMACÉN) REFERENCES ALMACÉN(ID),
FOREIGN KEY (ID_ARTÍCULO) REFERENCES ARTÍCULO(ID)
);
 
CREATE TABLE CLIENTE_COMPRA_ARTÍCULO_ALMACÉN (
ID INT PRIMARY KEY AUTO_INCREMENT, 
ID_CLIENTE INT , 
ID_ARTÍCULO INT , 
ID_ALMACÉN INT, 
FECHA DATETIME,
FOREIGN KEY (ID_ALMACÉN) REFERENCES ALMACÉN(ID),
FOREIGN KEY (ID_ARTÍCULO) REFERENCES ARTÍCULO(ID),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
);