DROP SCHEMA IF EXISTS REPASO_2;
CREATE SCHEMA REPASO_2;

USE REPASO_2;

CREATE TABLE CATEGORIA (
    ID INT PRIMARY KEY AUTO_INCREMENT ,
    NOMBRE VARCHAR(30),
    DESCRIPCION TINYTEXT
);

CREATE TABLE PLATO (
    ID INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
    NOMBRE VARCHAR(30),
    DESCRIPCION TEXT,
    FOTO MEDIUMBLOB,
    PRECIO_EN_EUROS DECIMAL(6, 2),
    ID_CATEGORIA INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE INGREDIENTE (
    ID INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
    NOMBRE VARCHAR(255),
    STOCK FLOAT,
    UNIDAD_MEDIDA_STOCK VARCHAR(30)
);

CREATE TABLE ALERGENOS_INGREDIENTE (
    ID_INGREDIENTE INT,
    ALERGENO VARCHAR(30),
    PRIMARY KEY (ID_INGREDIENTE, ALERGENO),
    FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTE(ID)
);

CREATE TABLE PLATO_USA_INGREDIENTE (
    ID_PLATO INT ,
    ID_INGREDIENTE INT,
    CANTIDAD FLOAT,
    UNIDAD_MEDIDA VARCHAR(50),
    PRIMARY KEY (ID_PLATO, ID_INGREDIENTE),
    FOREIGN KEY (ID_PLATO) REFERENCES PLATO(ID),
    FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTE(ID)
);