DROP SCHEMA IF EXISTS REPASO_1;
CREATE SCHEMA REPASO_1;

USE REPASO_1;

CREATE TABLE CAMIONERO(
	ID INT PRIMARY KEY AUTO_INCREMENT , 
    DNI CHAR (9) UNIQUE, #LO PONEMOS CUANDO EUNA COLUMNA ES CLARAMENTE CLAVE CANDIDATA
    NOMBRE VARCHAR(30),
    TELÉFONO VARCHAR (15),
    DIRECCIÓN VARCHAR (30),
    SALARIO DECIMAL (5,2),
    POBLACIÓN VARCHAR (30)
    
);
CREATE TABLE CAMIÓN(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    MATRICULA VARCHAR(10),
    MODELO VARCHAR(30),
    TIPO VARCHAR(30),
    POTENCIA SMALLINT
);
CREATE TABLE PROVINCIA (
    ID INT PRIMARY KEY,
    CODIGO CHAR(2) UNIQUE,
    NOMBRE VARCHAR(30)
);
CREATE TABLE PAQUETE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO VARCHAR(50),
    DESCRIPCION TINYTEXT,
    NOMBRE_DESTINATARIO VARCHAR(30),
    DIRECCION_DESTINATARIO VARCHAR(100),
    ID_PROVINCIA INT,
    
    FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID)
);
CREATE TABLE CAMIONERO_CONDUCE_CAMION (
    ID_CAMIONERO INT,
    ID_CAMION INT,
    FECHA DATE,
    
    PRIMARY KEY (ID_CAMIONERO, ID_CAMION, FECHA), #ES UNA CLAVE PRIMARIA COMPUESTA, NO SON 3 DISTINTAS
    FOREIGN KEY (ID_CAMIONERO) REFERENCES CAMIONERO(ID),
    FOREIGN KEY (ID_CAMION) REFERENCES CAMION(ID)
);

CREATE TABLE CAMIONERO_TRANSPORTA_PAQUETE (
    ID_CAMIONERO INT,
    ID_PAQUETE INT,
    PRIMARY KEY (ID_CAMIONERO, ID_PAQUETE),#ES UNA CABLE PRIMARIA COMPUESTA
    FOREIGN KEY (ID_CAMIONERO) REFERENCES CAMIONERO(ID),
    FOREIGN KEY (ID_PAQUETE) REFERENCES PAQUETE(ID)
);

