DROP SCHEMA IF EXISTS REPASO_3;
CREATE SCHEMA REPASO_3;

USE REPASO_3;


CREATE TABLE PELÍCULA (
	ID INT PRIMARY KEY AUTO_INCREMENT , 
	TÍTULO VARCHAR(30),
	AÑO SMALLINT, 
	NACIONALIDAD VARCHAR(30),
	ES_COLOR BOOL, #0 ES FALSO EL RESTO VERDADERO
	RESTRICCIÓN_EDAD TINYINT,
	RESUMEN TEXT
 );
 
CREATE TABLE PELÍCULA_TIENE_OBSERVACIÓN (
	ID_PELÍCULA INT  ,
	OBSERVACIÓN VARCHAR(200),
	PRIMARY KEY (ID_PELÍCULA,OBSERVACIÓN),
	FOREIGN KEY (ID_PELÍCULA) REFERENCES PELÍCULA(ID)
 ) ;
 
CREATE TABLE PELÍCULA_TIENE_IDIOMA (
	ID_PELÍCULA INT,
	IDIOMA VARCHAR (20),

	PRIMARY KEY (ID_PELÍCULA,IDIOMA),
	FOREIGN KEY (ID_PELÍCULA) REFERENCES PELÍCULA(ID)
) ; 

CREATE TABLE DIRECTOR (
	ID INT PRIMARY KEY AUTO_INCREMENT , 
	NOMBRE VARCHAR (30), 
	FECHA_NACIMIENTO DATE, 
	PAIS_ORIGEN VARCHAR (50)

); 
CREATE TABLE ACTOR (
	ID INT KEY AUTO_INCREMENT , 
	NOMBRE VARCHAR (30) , 
	NACIONALIDAD VARCHAR (50)
); 
CREATE TABLE ACTOR_ACTÚA_PELÍCULA (
	ID_ACTOR INT , 
	ID_PELÍCULA INT, 
	PERSONAJE VARCHAR (50),

	PRIMARY KEY (ID_ACTOR,ID_PELÍCULA,PERSONAJE),
	FOREIGN KEY (ID_ACTOR) REFERENCES ACTOR(ID),
	FOREIGN KEY (ID_PELÍCULA) REFERENCES PELÍCULA(ID)
); 
CREATE TABLE DIRECTOR_DIRIGE_PELÍCULA (
	ID_DIRECTOR INT, 
	ID_PELÍCULA INT,

	PRIMARY KEY (ID_DIRECTOR,ID_PELÍCULA),
	FOREIGN KEY (ID_DIRECTOR) REFERENCES DIRECTOR(ID),
	FOREIGN KEY (ID_PELÍCULA) REFERENCES PELÍCULA(ID)
);